openapi: 3.0.3
info:
  title: XQ Fitness Read Service API
  description: Read-only service for querying workout routines and related data
  version: 1.1.1
  contact:
    name: XQ Fitness Team

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /muscle-groups:
    get:
      summary: Get all muscle groups
      description: Retrieves a list of all available muscle groups
      operationId: getMuscleGroups
      tags:
        - Muscle Groups
      responses:
        '200':
          description: Successfully retrieved muscle groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MuscleGroup'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /routines:
    get:
      summary: Get all workout routines
      description: Retrieves a list of all workout routines
      operationId: getRoutines
      tags:
        - Routines
      parameters:
        - name: isActive
          in: query
          description: Filter by active status
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successfully retrieved routines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkoutRoutine'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /routines/{routineId}:
    get:
      summary: Get a specific workout routine
      description: Retrieves a workout routine with all its days and sets configuration
      operationId: getRoutineById
      tags:
        - Routines
      parameters:
        - name: routineId
          in: path
          description: ID of the routine to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully retrieved routine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutRoutineDetail'
        '404':
          description: Routine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /routines/{routineId}/days:
    get:
      summary: Get all workout days for a routine
      description: Retrieves all workout days for a specific routine
      operationId: getWorkoutDays
      tags:
        - Workout Days
      parameters:
        - name: routineId
          in: path
          description: ID of the routine
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully retrieved workout days
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkoutDayDetail'
        '404':
          description: Routine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /routines/{routineId}/weekly-report:
    get:
      summary: Get weekly report for a routine
      description: |
        Retrieves a weekly report showing the total number of sets per muscle group
        for the current week. The report aggregates sets data from the weekly snapshot
        if one exists. If no snapshot exists for the current week, returns an empty
        report with all muscle groups showing zero sets.
      operationId: getWeeklyReport
      tags:
        - Reports
      parameters:
        - name: routineId
          in: path
          description: ID of the routine to get report for
          required: true
          schema:
            type: integer
            format: int64
        - name: weekStartDate
          in: query
          description: Optional week start date (Monday) in ISO 8601 format (YYYY-MM-DD). If not provided, uses current week.
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Weekly report retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeeklyReportResponse'
        '404':
          description: Routine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    MuscleGroup:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 13
        name:
          type: string
          example: "Abductor"
        description:
          type: string
          example: "Hip abductor muscles (gluteus medius, gluteus minimus, tensor fasciae latae)"
        createdAt:
          type: string
          format: date-time

    WorkoutRoutine:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Push Pull Legs"
        description:
          type: string
          example: "3-day split focusing on push, pull, and leg movements"
        isActive:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    WorkoutRoutineDetail:
      allOf:
        - $ref: '#/components/schemas/WorkoutRoutine'
        - type: object
          properties:
            workoutDays:
              type: array
              items:
                $ref: '#/components/schemas/WorkoutDayDetail'

    WorkoutDay:
      type: object
      required:
        - id
        - routineId
        - dayNumber
        - dayName
      properties:
        id:
          type: integer
          format: int64
          example: 1
        routineId:
          type: integer
          format: int64
          example: 1
        dayNumber:
          type: integer
          example: 1
        dayName:
          type: string
          example: "Push Day"
        notes:
          type: string
          example: "Focus on chest and shoulders"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    WorkoutDayDetail:
      allOf:
        - $ref: '#/components/schemas/WorkoutDay'
        - type: object
          properties:
            sets:
              type: array
              items:
                $ref: '#/components/schemas/WorkoutDaySet'

    WorkoutDaySet:
      type: object
      required:
        - id
        - workoutDayId
        - muscleGroup
        - numberOfSets
      properties:
        id:
          type: integer
          format: int64
          example: 1
        workoutDayId:
          type: integer
          format: int64
          example: 1
        muscleGroup:
          $ref: '#/components/schemas/MuscleGroup'
        numberOfSets:
          type: integer
          minimum: 1
          example: 4
        notes:
          type: string
          example: "Focus on progressive overload"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    WeeklyReportResponse:
      type: object
      required:
        - routineId
        - weekStartDate
        - hasSnapshot
        - muscleGroupTotals
      properties:
        routineId:
          type: integer
          format: int64
          example: 1
        weekStartDate:
          type: string
          format: date
          description: Monday date of the current week (ISO 8601 format YYYY-MM-DD)
          example: "2024-12-02"
        hasSnapshot:
          type: boolean
          description: Whether a snapshot exists for this week
          example: true
        snapshotCreatedAt:
          type: string
          format: date-time
          description: When the snapshot was created (null if no snapshot)
          example: "2024-12-07T10:30:00Z"
          nullable: true
        muscleGroupTotals:
          type: array
          description: Total sets per muscle group aggregated across all workout days
          items:
            $ref: '#/components/schemas/MuscleGroupTotal'
    
    MuscleGroupTotal:
      type: object
      required:
        - muscleGroup
        - totalSets
      properties:
        muscleGroup:
          $ref: '#/components/schemas/MuscleGroup'
        totalSets:
          type: integer
          description: Total number of sets for this muscle group across all workout days in the routine
          minimum: 0
          example: 12

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "INTERNAL_ERROR"
        message:
          type: string
          example: "An unexpected error occurred"
        timestamp:
          type: string
          format: date-time
